### ISSUE TITLE
not work in nuke 13.0

### ISSUE THREAD

**Issue by lucky0511** [tarantulaVFX/Kitsu4Nuke#3]
```
Traceback (most recent call last):
  File "C:/Users/VFX-Admin/.nuke/Kitsu4Nuke/menu.py", line 12, in <module>
    import Kitsu4Nuke
  File "C:/Users/VFX-Admin/.nuke/Kitsu4Nuke\Kitsu4Nuke.py", line 9, in <module>
    from KitsuLogin import KitsuLogin
  File "C:/Users/VFX-Admin/.nuke/Kitsu4Nuke\KitsuLogin.py", line 9, in <module>
    from KitsuUtil import KitsuSession, setConfig, getConfig, empty_conf
ImportError: cannot import name 'KitsuSession' from 'KitsuUtil' (C:/Users/VFX-Admin/.nuke/Kitsu4Nuke\KitsuUtil\__init__.py)


```
Please help me fix it, your script not working in nuke 13 or later. please dont drop it
